apiVersion: v1
kind: Namespace
metadata:
  name: notes-space 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  labels:
    app: notes-app
  namespace: notes-space    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: ritikkkk/notes-image
        ports:
        - containerPort: 5000

---

kind: Service
apiVersion: v1
metadata:
  name: notes-app-service
  namespace: notes-space
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  
  

