name: aks_cluster
on: push
jobs:
    cluster:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4

            - name: login docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - name: Set up Docker Buildx
            #   # uses: docker/setup-buildx-action@v3
            #   run: docker build -t notes-image .
            
            - name: Build and push multi-arch image
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ritikkkk/notes-image:latest

            - name:  Azure login
              run: az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4

            - name:  connect cluster
              run: az aks get-credentials --resource-group trial-aks --name ritik-cluster --overwrite-existing

            - name:  running deploy file
              run: |
                cd k8s
                kubectl apply -f k8s.yml

            - name:  getting the external ip 
              run: echo " public ip $(kubectl get svc -n notes-space)"
            
            
